### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by dqunbp** [gimenete/github-jest-snapshots#2]
Hi!
I trying to add you plugin to my workflow.
My `yml`
```yaml
name: Node.js CI

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm t -- --coverage
      env:
        CI: true 

    - name: Jest Snapshots
      uses: gimenete/github-jest-snapshots@1.0

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Coverage Report
        # Directory containing files to upload
        path: ./coverage
```
But it is failed with 401 error
Job log
```sh
Run gimenete/github-jest-snapshots@1.0
/usr/bin/docker run --name e87b528c37f1d1c3014005abe597343f827659_754f5d --label e87b52 --workdir /github/workspace --rm -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v ...
...
npm WARN @lingui/cli@2.9.1 requires a peer of typescript@2 || 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.0 requires a peer of eslint-plugin-flowtype@3.x but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

audited 920420 packages in 9.756s

54 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Error Error: Received status code 401
    at IncomingMessage.res.on (/action/lib/request.js:13:25)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

What's wrong?
